#!/bin/bash
docker stop lesezeichen; docker rm lesezeichen;  docker run -d -v /home/konrad/volumes/lesezeichen/data:/opt/data -v /home/konrad/volumes/lesezeichen/bin:/opt/bin --link couchdb:db --name lesezeichen -p 8087:8087 kordano/lesezeichen
