#!/bin/bash
docker stop lesezeichen; docker rm lesezeichen;  docker run -d -v /home/konrad/volumes/lesezeichen/data:/opt/data -v /home/konrad/volumes/lesezeichen/bin:/opt/bin --name bookie -p 8087:8087 kordano/bookie
